export const INITIAL_EQUIPMENT = [
  {
    id: 'eq-001',
    tipo: 'Perfuratriz Hidráulica',
    marca: 'Sandvik',
    modelo: 'Ranger DX800i / DP1500i',
    numeroSerie: 'SN-SANDVIK-98421',
    numeroInventario: 'PRF-01',
    anoFabricacao: 2021,
    dataAquisicao: '2021-04-15',
    valorCompra: 3450000.00,
    fornecedor: 'Sandvik Mining & Construction do Brasil',
    localizacao: 'Mina Norte - Frente de Lavra 02',
    status: 'Operacional',
    vidaUtilEstimada: '15.000 horas',
    prazoGarantia: '2023-04-15 (Expirada)',
    fotoUrl: 'https://images.unsplash.com/photo-1578575437130-527eed3abbec?auto=format&fit=crop&w=800&q=80',
    horimetroAtual: 4850,
    nr12Status: 'Adequado / Conforme',
    nr12DataUltimaInspecao: '2026-01-10',
    nr12DataProximaInspecao: '2026-07-10',
    nr19Aplicavel: true,
    nr19Status: 'Conforme (Explosivos / Detonação)',
    operadoresHabilitados: [
      { nome: 'Carlos Eduardo Silva', matricula: 'OP-4091' },
      { nome: 'Roberto Mendes Santos', matricula: 'OP-3822' }
    ]
  },
  {
    id: 'eq-002',
    tipo: 'Escavadeira Hidráulica',
    marca: 'Caterpillar',
    modelo: 'CAT 336 GC',
    numeroSerie: 'SN-CAT336-77312',
    numeroInventario: 'ESC-03',
    anoFabricacao: 2022,
    dataAquisicao: '2022-08-20',
    valorCompra: 1890000.00,
    fornecedor: 'Sotreq Caterpillar',
    localizacao: 'Obra Terraplanagem Lote 03',
    status: 'Em Manutenção',
    vidaUtilEstimada: '20.000 horas',
    prazoGarantia: '2024-08-20 (Expirada)',
    fotoUrl: 'https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?auto=format&fit=crop&w=800&q=80',
    horimetroAtual: 6120,
    nr12Status: 'Pendente de Inspeção',
    nr12DataUltimaInspecao: '2025-06-15',
    nr12DataProximaInspecao: '2026-06-15',
    nr19Aplicavel: false,
    nr19Status: 'Não Aplicável',
    operadoresHabilitados: [
      { nome: 'Marcos Vinicius Lima', matricula: 'OP-1044' },
      { nome: 'Joaquim Barbosa', matricula: 'OP-2291' }
    ]
  },
  {
    id: 'eq-003',
    tipo: 'Compressor de Ar',
    marca: 'Atlas Copco',
    modelo: 'XAS 188 Cud High Pressure',
    numeroSerie: 'SN-ATL-55201',
    numeroInventario: 'CMP-02',
    anoFabricacao: 2023,
    dataAquisicao: '2023-02-10',
    valorCompra: 420000.00,
    fornecedor: 'Atlas Copco Brasil',
    localizacao: 'Túnel de Acesso Central',
    status: 'Operacional',
    vidaUtilEstimada: '12.000 horas',
    prazoGarantia: '2025-02-10',
    fotoUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
    horimetroAtual: 2480,
    nr12Status: 'Adequado / Conforme',
    nr12DataUltimaInspecao: '2026-03-01',
    nr12DataProximaInspecao: '2026-09-01',
    nr19Aplicavel: false,
    nr19Status: 'Não Aplicável',
    operadoresHabilitados: [
      { nome: 'Fernando Alencar', matricula: 'OP-5102' }
    ]
  },
  {
    id: 'eq-004',
    tipo: 'Gerador Silenciado',
    marca: 'Cummins',
    modelo: 'C250D6 250 kVA',
    numeroSerie: 'SN-CUM-88402',
    numeroInventario: 'GER-01',
    anoFabricacao: 2020,
    dataAquisicao: '2020-11-05',
    valorCompra: 310000.00,
    fornecedor: 'Cummins Brasil Distribuidora',
    localizacao: 'Canteiro Central de Operações',
    status: 'Operacional',
    vidaUtilEstimada: '18.000 horas',
    prazoGarantia: '2022-11-05 (Expirada)',
    fotoUrl: 'https://images.unsplash.com/photo-1513828583688-c52646db42da?auto=format&fit=crop&w=800&q=80',
    horimetroAtual: 8950,
    nr12Status: 'Adequado / Conforme',
    nr12DataUltimaInspecao: '2026-02-14',
    nr12DataProximaInspecao: '2026-08-14',
    nr19Aplicavel: false,
    nr19Status: 'Não Aplicável',
    operadoresHabilitados: [
      { nome: 'Eletricista Renato Souza', matricula: 'MA-9011' }
    ]
  },
  {
    id: 'eq-005',
    tipo: 'Pá Carregadeira',
    marca: 'Komatsu',
    modelo: 'WA380-6 Heavy Duty',
    numeroSerie: 'SN-KOM-33910',
    numeroInventario: 'PAC-04',
    anoFabricacao: 2022,
    dataAquisicao: '2022-05-18',
    valorCompra: 1650000.00,
    fornecedor: 'Komatsu do Brasil',
    localizacao: 'Pedreira Sul - Britagem',
    status: 'Parado / Avariado',
    vidaUtilEstimada: '16.000 horas',
    prazoGarantia: '2024-05-18 (Expirada)',
    fotoUrl: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=800&q=80',
    horimetroAtual: 5490,
    nr12Status: 'Adequado / Conforme',
    nr12DataUltimaInspecao: '2025-11-20',
    nr12DataProximaInspecao: '2026-05-20',
    nr19Aplicavel: false,
    nr19Status: 'Não Aplicável',
    operadoresHabilitados: [
      { nome: 'Diego Castro', matricula: 'OP-3012' }
    ]
  }
];

export const INITIAL_MAINTENANCE = [
  {
    id: 'mn-101',
    equipamentoId: 'eq-001',
    dataRevisao: '2026-07-10',
    horimetro: 4750,
    tipo: 'Preventiva',
    itensServicos: 'Troca de óleo do motor diesel, substituição dos filtros de combustível e lubrificante, inspeção das mangueiras de alta pressão do martelo perfurador.',
    pecas: [
      { id: 'p-1', nome: 'Filtro de Óleo Lubrificante Sandvik', quantidade: 2, valorUnitario: 450.00, valorTotal: 900.00 },
      { id: 'p-2', nome: 'Elemento Filtrante de Combustível', quantidade: 3, valorUnitario: 320.00, valorTotal: 960.00 },
      { id: 'p-3', nome: 'Óleo Sintético 15W40 (Litros)', quantidade: 40, valorUnitario: 42.00, valorTotal: 1680.00 }
    ],
    custoPecas: 3540.00,
    custoMaoDeObra: 2800.00,
    custoTotal: 6340.00,
    downtimeHoras: 8,
    mecanicoResponsavel: 'Eng. Arnaldo Ribeiro',
    oficinaTipo: 'interna',
    oficinaNome: 'Oficina Central da Mina',
    causaFalhaDiagnostico: 'Manutenção preventiva programada de 500 horas. Parâmetros operacionais normais.',
    statusOS: 'Concluída',
    proximaDataManutencao: '2026-10-10',
    proximoHorimetroManutencao: 5250
  },
  {
    id: 'mn-102',
    equipamentoId: 'eq-002',
    dataRevisao: '2026-07-22',
    horimetro: 6120,
    tipo: 'Corretiva',
    itensServicos: 'Rompimento do mangote hidráulico do cilindro da caçamba. Limpeza da área atingida por óleo, substituição do mangote e sangria do sistema.',
    pecas: [
      { id: 'p-4', nome: 'Mangote Hidráulico 1" 4SP alta pressão', quantidade: 1, valorUnitario: 1450.00, valorTotal: 1450.00 },
      { id: 'p-5', nome: 'Fluido Hidráulico ISO VG 68 (Litros)', quantidade: 80, valorUnitario: 38.00, valorTotal: 3040.00 },
      { id: 'p-6', nome: 'Kits O-Ring vedação hidráulica', quantidade: 2, valorUnitario: 180.00, valorTotal: 360.00 }
    ],
    custoPecas: 4850.00,
    custoMaoDeObra: 3500.00,
    custoTotal: 8350.00,
    downtimeHoras: 14,
    mecanicoResponsavel: 'Técnico Sotreq (Terceirizado)',
    oficinaTipo: 'terceirizada',
    oficinaNome: 'Sotreq Assistência Técnica Autorizada',
    causaFalhaDiagnostico: 'Fadiga por atrito do mangote na estrutura da lança durante operação de rocha pesada.',
    statusOS: 'Em Andamento',
    proximaDataManutencao: '2026-08-15',
    proximoHorimetroManutencao: 6350
  },
  {
    id: 'mn-103',
    equipamentoId: 'eq-003',
    dataRevisao: '2026-06-05',
    horimetro: 2250,
    tipo: 'Preventiva',
    itensServicos: 'Revisão periódica do separador de água e ar, substituição do filtro de admissão do elemento compressor, reaperto de conexões elétricas.',
    pecas: [
      { id: 'p-7', nome: 'Filtro Separador Ar/Óleo Atlas Copco', quantidade: 1, valorUnitario: 1200.00, valorTotal: 1200.00 },
      { id: 'p-8', nome: 'Filtro de Ar Primário', quantidade: 1, valorUnitario: 540.00, valorTotal: 540.00 }
    ],
    custoPecas: 1740.00,
    custoMaoDeObra: 1200.00,
    custoTotal: 2940.00,
    downtimeHoras: 4,
    mecanicoResponsavel: 'Mário Sergio Nogueira',
    oficinaTipo: 'interna',
    oficinaNome: 'Oficina Móvel 01',
    causaFalhaDiagnostico: 'Preventiva de 250 horas concluída conforme manual do fabricante.',
    statusOS: 'Concluída',
    proximaDataManutencao: '2026-07-28',
    proximoHorimetroManutencao: 2500
  },
  {
    id: 'mn-104',
    equipamentoId: 'eq-005',
    dataRevisao: '2026-07-24',
    horimetro: 5490,
    tipo: 'Corretiva',
    itensServicos: 'Sobreaquecimento da transmissão da pá carregadeira durante carregamento de blocos. Aguardando diagnóstico e desmontagem do conversor de torque.',
    pecas: [],
    custoPecas: 0,
    custoMaoDeObra: 1500.00,
    custoTotal: 1500.00,
    downtimeHoras: 28,
    mecanicoResponsavel: 'Eng. Arnaldo Ribeiro',
    oficinaTipo: 'interna',
    oficinaNome: 'Oficina Central da Mina',
    causaFalhaDiagnostico: 'Desgaste severo dos discos da embreagem da transmissão e obstrução do radiador de óleo.',
    statusOS: 'Aberta',
    proximaDataManutencao: '2026-08-01',
    proximoHorimetroManutencao: 5500
  },
  {
    id: 'mn-105',
    equipamentoId: 'eq-004',
    dataRevisao: '2026-05-12',
    horimetro: 8500,
    tipo: 'Preventiva',
    itensServicos: 'Revisão de 500h do grupo gerador. Teste de carga, troca do óleo lubrificante, calibração do regulador automático de tensão (AVR) e teste do QTA.',
    pecas: [
      { id: 'p-9', nome: 'Conjunto de Filtros Cummins Heavy Duty', quantidade: 1, valorUnitario: 1100.00, valorTotal: 1100.00 },
      { id: 'p-10', nome: 'Bateria Estacionária 150Ah 12V', quantidade: 1, valorUnitario: 980.00, valorTotal: 980.00 }
    ],
    custoPecas: 2080.00,
    custoMaoDeObra: 1400.00,
    custoTotal: 3480.00,
    downtimeHoras: 6,
    mecanicoResponsavel: 'Eletricista Renato Souza',
    oficinaTipo: 'interna',
    oficinaNome: 'Setor Elétrico Canteiro',
    causaFalhaDiagnostico: 'Preventiva periódica efetuada com sucesso. Equipamento aprovado para uso continuo.',
    statusOS: 'Concluída',
    proximaDataManutencao: '2026-08-10',
    proximoHorimetroManutencao: 9000
  }
];
